services:
  - type: web
    name: shopify-analytics-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGIN
        value: https://your-frontend-domain.com
